name: Test deployment

on:
  pull_request:
    branches: [main]
    paths: [website/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Test build
        working-directory: website
        run: |
          npm ci
          npm run build